// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// stimgate_cppmden.cpp
cpp11::list stimgate_cpPmden(std::vector<double> x);
extern "C" SEXP _stimgate_stimgate_cpPmden(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(stimgate_cpPmden(cpp11::as_cpp<cpp11::decay_t<std::vector<double>>>(x)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_stimgate_stimgate_cpPmden", (DL_FUNC) &_stimgate_stimgate_cpPmden, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_stimgate(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
