name: "Copilot Setup Steps"

on:
  workflow_dispatch:

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 0. Set up the environment
      - name: Install system dependencies setup-r does not
        run: |
          sudo apt-get update -y
          sudo apt-get install --no-install-recommends -y \
            libcurl4-openssl-dev libfontconfig1-dev libfreetype6-dev \
            libgit2-dev libjpeg-dev libpng-dev libx11-dev pandoc

      # 1. Get the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up R
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2' # The R version to download (if necessary) and use.
          # Use "renv" to retrieve R version recorded in renv.lock file.

      # 3. Set up CRAN mirror
      - name: Ensure and set CRAN mirror
        run: |
          RHOME=$(R RHOME | tr -d '"')
          f=${RHOME}/etc/Rprofile.site
          echo "Appending CRAN mirror to: $f"
          sudo mkdir -p "$(dirname "$f")"
          sudo touch "$f"
          echo 'if (is.null(getOption("repos")[["CRAN"]])) options(repos = c(getOption("repos"), CRAN = "https://cran.rstudio.com"))' | sudo tee -a "$f"

      # 4. Set up pak
      - name: Install pak and BiocManager before using pak
        run: |
          Rscript -e 'if (!requireNamespace("pak", quietly = TRUE)) utils::install.packages("pak", repos = "https://cran.r-project.org")'
          Rscript -e 'if (!requireNamespace("BiocManager", quietly = TRUE)) utils::install.packages("BiocManager", repos = "https://cran.r-project.org")'
      
      # 5. Restore R packages
      - uses: r-lib/actions/setup-renv@v2
        env:
          RENV_CONFIG_PAK_ENABLED: "FALSE"
        with:
          profile: '"non_bioc_container"'
          bypass-cache: "never" # cache is not used otherwise
