name: "Copilot Setup Steps"

on:
  workflow_dispatch:

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. Get the code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev

      # 2. Set up R
      - name: Install R
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends r-base

      # 3. Cache R packages
      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      # 4. Restore R package dependencies
      - name: Restore R package dependencies
        run: |
          Rscript -e "renv::restore()"

