name: "Copilot Setup Steps"

on:
  workflow_dispatch:

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. Get the code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev

      # 2. Set up R
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2' # The R version to download (if necessary) and use.
          # Use "renv" to retrieve R version recorded in renv.lock file.
      - uses: r-lib/actions/setup-renv@v2
        with:
          profile: '"non_bioc_container"'
