name: "Copilot Setup Steps"

on:
  workflow_dispatch:

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. Get the code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev

      # 2. Set up R
      - name: Install R
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
              software-properties-common dirmngr ca-certificates gnupg curl \
              libcurl4-openssl-dev libfontconfig1-dev libfreetype6-dev libgit2-dev \
              libjpeg-dev libpng-dev libx11-dev pandoc

          # 1. Fetch and install the rig GPG key
          curl -fsSL https://rig.r-pkg.org/deb/rig.gpg \
            | sudo tee /etc/apt/trusted.gpg.d/rig.gpg > /dev/null

          # 2. Add the rig APT repository
          echo "deb [arch=$(dpkg --print-architecture)] http://rig.r-pkg.org/deb rig main" \
            | sudo tee /etc/apt/sources.list.d/rig.list

          # 3. Update and install the rig manager
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends r-rig

          # 4. Use rig to install R 4.4.2 and make it the default
          rig add 4.4.2
          rig default 4.4.2


      # 3. Cache R packages
      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Configure Bioconductor
        run: |
          Rscript -e "options(repos = BiocManager::repositories())"
          Rscript -e "BiocManager::install(version = '3.20', ask = FALSE)"

      # 4. Restore R package dependencies
      - name: Restore R package dependencies
        run: |
          Rscript -e "renv::restore()"

